server:
  port: 8080
#  servlet:
#    context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/warehouse?serverTimezone=UTC

#thymeleaf:
#  prefix: classpath:/templates/
#  check-template-location: true
#  suffix: .html
#  mode: HTML
#  encoding: UTF-8
#  cache: false

mybatis:
  type-aliases-package: cn.edu.gues.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true




